services:
  pgdatabase: #name of the database that is required in pgadmin when registering the server
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=weather
    volumes:
      - "./weather_postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  prefect-server:
    image: prefecthq/prefect
    environment:
      - PREFECT_SERVER_DATABASE_URL=postgresql+psycopg2://root:root@pgdatabase:5432/weather
      - PREFECT_SERVER_UI_ENABLED=true
    ports:
      - "4200:4200"  # Port for Prefect UI
    depends_on:
      - pgdatabase
    restart: always

  prefect-agent:
    image: prefecthq/prefect
    command: prefect agent start --label default
    depends_on:
      - prefect-server
    restart: always