services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=weather
    volumes:
      - "./weather_postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d weather"]
      interval: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

  prefect-server:
    image: prefecthq/prefect:2.20.17-python3.12
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://root:root@pgdatabase:5432/weather
      - PREFECT_API_URL=http://0.0.0.0:4200
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_SERVER_API_PORT=4200    
    command: ["prefect", "server", "start"]
    ports:
      - "4200:4200"
    depends_on:
      - pgdatabase
    restart: always

  prefect-worker:
    image: prefecthq/prefect:2.20.17-python3.12
    command: ["prefect", "worker", "start", "-p", "default"]
    depends_on:
      - prefect-server
    restart: always
